{% set version = '0.99.16' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rgl
  version: {{ version|replace("-", "_") }}

source:
  fn: rgl_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/rgl_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rgl/rgl_{{ version }}.tar.gz
  sha256: 692a545ed2ff0f5e15289338736f0e3c092667574c43ac358d8004901d7a1a61

build:
  merge_build_host: True  # [win]
  number: 1000
  skip: True              # [osx]
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: MASS, rmarkdown, deldir, orientlib, lattice, misc3d, rstudioapi, magick
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake          # [not win]
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-crosstalk
    - r-htmltools
    - r-htmlwidgets
    - r-jsonlite >=0.9.20
    - r-knitr
    - r-magrittr
    - r-manipulatewidget >=0.9.0
    - r-shiny
    - libglu                     # [linux]
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-crosstalk
    - r-htmltools
    - r-htmlwidgets
    - r-jsonlite >=0.9.20
    - r-knitr
    - r-magrittr
    - r-manipulatewidget >=0.9.0
    - r-shiny
    - libglu                     # [linux]

test:
  commands:
    - $R -e "library('rgl')"           # [not win]
    - "\"%R%\" -e \"library('rgl')\""  # [win]

about:
  home: https://r-forge.r-project.org/projects/rgl/
  license: GPL
  summary: Provides medium to high level functions for 3D interactive graphics, including functions
    modelled on base graphics (plot3d(), etc.) as well as functions for constructing
    representations of geometric objects (cube3d(), etc.).  Output may be on screen
    using OpenGL, or to various standard 3D file formats including WebGL, PLY, OBJ,
    STL as well as 2D image formats, including PNG, Postscript, SVG, PGF.
  license_family: GPL

extra:
  recipe-maintainers:
    - dpryan79
    - cbrueffer
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
